import type { NextPage } from "next";
import Head from "next/head";
import Layout from "components/layout";
import Carousel from "components/carousel";
import FashionNewsItem from "components/fashion-news-item";
import { gql } from "@apollo/client";
import client from "apollo-client";
import Card from "components/product-card";
import PageContainer from "components/layout/page-container";
import { allProducts } from "__mocks__/mocks";

interface FashionNewsType {
  id: number | string;
  img: string;
}

interface ProductType {
  id: number;
  name: string;
  price: string;
  main_image: string;
}

export const FASHION_NEWS = gql`
  query GetFashionNews {
    fashionNews {
      id
      img
    }
  }
`;

export const PRODUCTS = gql`
  query GetProducts {
    products {
      id
      name
      price
      main_image
    }
  }
`;

const Home: NextPage<{
  fashionNews: FashionNewsType[];
  products: ProductType[];
}> = ({ fashionNews, products }) => {
  return (
    <div>
      <Head>
        <title>Demo Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout fullWidth>
        <section className="max-w-[90%] h-1/2 m-auto mt-10">
          <Carousel>
            {fashionNews.map((item) => (
              <FashionNewsItem key={item.id} item={item} />
            ))}
          </Carousel>
        </section>
        <section className="w-[80%] m-auto mt-32">
          <PageContainer grid fullWidth>
            {products.map((product) => (
              <Card key={product.id} product={product} />
            ))}
          </PageContainer>
        </section>
      </Layout>
    </div>
  );
};

export async function getStaticProps() {
  const fashionNewsResponse = await client.query({
    query: FASHION_NEWS,
  });
  const productsResponse = await client.query({
    query: PRODUCTS,
  });
  return {
    props: {
      fashionNews: fashionNewsResponse.data.fashionNews,
      products: productsResponse.data.products,
    },
  };
}

export default Home;
