import Head from "next/head";
import { Fragment } from "react";
import Header from "../header";
import PageContainer from "./page-container";

export interface LayoutProps {
  fullWidth?: boolean | undefined;
  grid?: boolean | undefined;
  children?: React.ReactNode;
}

const Layout = ({
  title,
  fullWidth,
  grid,
  children,
}: LayoutProps & {
  title: string;
}) => {
  return (
    <Fragment>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Header />
      <PageContainer fullWidth={fullWidth} grid={grid} children={children} />
      {/* <Footer /> */}
    </Fragment>
  );
};

export default Layout;
